import { useEffect, useState } from "react";

/**
 * Monthly UK trade-in prices of phones, tablets and watches, one series per variant (capacity, network,
 * and for tablets / watches CPU, RAM, case size and material), in EUR: each month's GBP
 * price converted at that month's ECB reference rate (the GBP original stays in the database).
 * `src/data/tradein-history.json` is a copy of the MongoDB collection `tradeInPriceHistory`,
 * regenerated by `B2C-Backend/ml/import_tradein.py` on every import: the tool runs without
 * database access, so it reads the copy.
 */
export type TradeInVariant = {
  storage: string | null;
  network: string | null;
  /** Watches: case size ("45mm") and material ("Titanium"). */
  size?: string;
  material?: string;
  /** Surface tablets: processor and memory. */
  cpu?: string;
  ram?: string;
  /** First month of the series, "YYYY-MM". */
  start: string;
  /** One price per month from `start`; null = no quote that month. */
  prices: (number | null)[];
};
export const TRADEIN_CATEGORIES = ["phone", "tablet", "watch"] as const;
export type TradeInCategory = (typeof TRADEIN_CATEGORIES)[number];
export type TradeInModel = { category: TradeInCategory; launch: string; launchPriceExVat: number | null; variants: TradeInVariant[] };
export type TradeInSnapshot = { source: string; market: string; currency: "EUR"; sourceCurrency: "GBP"; generatedAt: string; models: Record<string, TradeInModel> };

let pending: Promise<TradeInSnapshot> | null = null;
/** Loaded on first use only (≈270 kB), in its own chunk. */
export const loadTradeIn = () =>
  (pending ??= import("@/data/tradein-history.json").then((m) => m.default as unknown as TradeInSnapshot));

export function useTradeIn(): TradeInSnapshot | undefined {
  const [data, setData] = useState<TradeInSnapshot>();
  useEffect(() => {
    let live = true;
    loadTradeIn().then((d) => live && setData(d)).catch(() => undefined);
    return () => { live = false; };
  }, []);
  return data;
}

export const tradeInKey = (brand: string, model: string) => `${brand}::${model}`;

export const addMonths = (month: string, n: number) => {
  const [y, m] = month.split("-").map(Number);
  const d = new Date(Date.UTC(y, m - 1 + n, 1));
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}`;
};
export const monthsBetween = (a: string, b: string) => {
  const [ya, ma] = a.split("-").map(Number);
  const [yb, mb] = b.split("-").map(Number);
  return (yb - ya) * 12 + mb - ma;
};

export const variantLabel = (v: Omit<TradeInVariant, "start" | "prices">) =>
  [v.size, v.material, v.cpu, v.ram && `${v.ram} RAM`, v.storage, v.network].filter(Boolean).join(" · ") || "—";

const LABEL_FIELDS = ["size", "material", "cpu", "ram", "storage", "network"] as const;

/**
 * Short labels for variants shown together: only the attributes that differ between them
 * ("128GB", "256GB" rather than "128GB · Wi-Fi", "256GB · Wi-Fi"). A lone variant keeps its full label.
 */
export function variantLabels(variants: TradeInVariant[]): string[] {
  if (variants.length <= 1) return variants.map(variantLabel);
  const differ = LABEL_FIELDS.filter((f) => new Set(variants.map((v) => v[f] ?? "")).size > 1);
  return variants.map((v) => differ.map((f) => (f === "ram" && v.ram ? `${v.ram} RAM` : v[f])).filter(Boolean).join(" · ") || variantLabel(v));
}

export const monthLabel = (month: string, style: "short" | "long" = "short") =>
  new Date(`${month}-01T00:00:00Z`).toLocaleDateString("fr-FR", { month: style === "short" ? "short" : "long", year: "numeric", timeZone: "UTC" });

export const money = (n?: number | null) =>
  n === undefined || n === null ? "—" : n.toLocaleString("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 });

/** Price of a variant in a given month (undefined when not quoted). */
export const priceAt = (v: TradeInVariant, month: string) => {
  const i = monthsBetween(v.start, month);
  return i >= 0 && i < v.prices.length ? v.prices[i] ?? undefined : undefined;
};

/** Latest quoted price of a variant and its month. */
export function latest(v: TradeInVariant): { price: number; month: string } | undefined {
  for (let i = v.prices.length - 1; i >= 0; i--) {
    const p = v.prices[i];
    if (p !== null) return { price: p, month: addMonths(v.start, i) };
  }
  return undefined;
}

/** Relative change over the last `months` months (from the latest quote), when both ends are quoted. */
export function change(v: TradeInVariant, months: number): number | undefined {
  const last = latest(v);
  if (!last) return undefined;
  const before = priceAt(v, addMonths(last.month, -months));
  return before ? last.price / before - 1 : undefined;
}

type Latest = { price: number; month: string };
export type VariantFilter = Partial<Pick<TradeInVariant, "storage" | "size" | "cpu" | "ram">>;

/**
 * Latest price of the variants matching a price-grid row ({ storage: "256GB" }, { size: "45mm" },
 * { cpu: "i5", ram: "16GB", storage: "256GB" }): the most recent quote, and among variants quoted that
 * month (Wi-Fi / 5G, materials…) the highest. An empty row ("All") gets the lowest current price.
 */
export function latestFor(m: TradeInModel, row: VariantFilter): Latest | undefined {
  const fields = (Object.keys(row) as (keyof VariantFilter)[]).filter((f) => row[f]);
  const found = m.variants
    .filter((v) => fields.every((f) => v[f] === row[f]))
    .map(latest)
    .filter((l): l is Latest => !!l);
  if (!found.length) return undefined;
  const newest = found.reduce((a, b) => (b.month > a ? b.month : a), "");
  const current = found.filter((l) => l.month === newest).map((l) => l.price);
  return { month: newest, price: fields.length ? Math.max(...current) : Math.min(...current) };
}

/** Most recent month quoted for a model. */
export const lastMonth = (m: TradeInModel) => m.variants.map(latest).reduce((a, l) => (l && l.month > a ? l.month : a), "");
