import { useEffect, useState } from "react";

/**
 * Monthly UK trade-in prices, one series per capacity / network variant, in EUR: each month's GBP
 * price converted at that month's ECB reference rate (the GBP original stays in the database).
 * `src/data/tradein-history.json` is a copy of the MongoDB collection `tradeInPriceHistory`,
 * regenerated by `B2C-Backend/ml/import_tradein.py` on every import: the tool runs without
 * database access, so it reads the copy.
 */
export type TradeInVariant = {
  storage: string | null;
  network: string | null;
  /** First month of the series, "YYYY-MM". */
  start: string;
  /** One price per month from `start`; null = no quote that month. */
  prices: (number | null)[];
};
export type TradeInModel = { launch: string; launchPriceExVat: number | null; variants: TradeInVariant[] };
export type TradeInSnapshot = { source: string; market: string; currency: "EUR"; sourceCurrency: "GBP"; generatedAt: string; models: Record<string, TradeInModel> };

let pending: Promise<TradeInSnapshot> | null = null;
/** Loaded on first use only (≈200 kB), in its own chunk. */
export const loadTradeIn = () =>
  (pending ??= import("@/data/tradein-history.json").then((m) => m.default as unknown as TradeInSnapshot));

export function useTradeIn(): TradeInSnapshot | undefined {
  const [data, setData] = useState<TradeInSnapshot>();
  useEffect(() => {
    let live = true;
    loadTradeIn().then((d) => live && setData(d)).catch(() => undefined);
    return () => { live = false; };
  }, []);
  return data;
}

export const tradeInKey = (brand: string, model: string) => `${brand}::${model}`;

export const addMonths = (month: string, n: number) => {
  const [y, m] = month.split("-").map(Number);
  const d = new Date(Date.UTC(y, m - 1 + n, 1));
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}`;
};
export const monthsBetween = (a: string, b: string) => {
  const [ya, ma] = a.split("-").map(Number);
  const [yb, mb] = b.split("-").map(Number);
  return (yb - ya) * 12 + mb - ma;
};

export const variantLabel = (v: Pick<TradeInVariant, "storage" | "network">) => [v.storage, v.network].filter(Boolean).join(" ") || "—";

export const monthLabel = (month: string, style: "short" | "long" = "short") =>
  new Date(`${month}-01T00:00:00Z`).toLocaleDateString("fr-FR", { month: style === "short" ? "short" : "long", year: "numeric", timeZone: "UTC" });

export const money = (n?: number | null) =>
  n === undefined || n === null ? "—" : n.toLocaleString("fr-FR", { style: "currency", currency: "EUR", maximumFractionDigits: 0 });

/** Price of a variant in a given month (undefined when not quoted). */
export const priceAt = (v: TradeInVariant, month: string) => {
  const i = monthsBetween(v.start, month);
  return i >= 0 && i < v.prices.length ? v.prices[i] ?? undefined : undefined;
};

/** Latest quoted price of a variant and its month. */
export function latest(v: TradeInVariant): { price: number; month: string } | undefined {
  for (let i = v.prices.length - 1; i >= 0; i--) {
    const p = v.prices[i];
    if (p !== null) return { price: p, month: addMonths(v.start, i) };
  }
  return undefined;
}

/** Relative change over the last `months` months (from the latest quote), when both ends are quoted. */
export function change(v: TradeInVariant, months: number): number | undefined {
  const last = latest(v);
  if (!last) return undefined;
  const before = priceAt(v, addMonths(last.month, -months));
  return before ? last.price / before - 1 : undefined;
}

/**
 * Latest price per capacity (network variants of one capacity: the most recent, then the highest),
 * plus the lowest across capacities for "All capacities".
 */
export function latestByStorage(m: TradeInModel): { byStorage: Map<string, { price: number; month: string }>; lowest?: { price: number; month: string } } {
  const byStorage = new Map<string, { price: number; month: string }>();
  for (const v of m.variants) {
    const l = latest(v);
    if (!l || !v.storage) continue;
    const prev = byStorage.get(v.storage);
    if (!prev || l.month > prev.month || (l.month === prev.month && l.price > prev.price)) byStorage.set(v.storage, l);
  }
  const all = [...byStorage.values()];
  const newest = all.reduce((a, b) => (b.month > a ? b.month : a), "");
  const lowest = all.filter((x) => x.month === newest).sort((a, b) => a.price - b.price)[0];
  return { byStorage, lowest };
}
